{"uuid": "35c2ae4e-5ad2-4d29-b67b-804d6189b274", "children": ["ae41dd5d-8d89-4118-9f61-d872a6a9d241", "45908691-6886-41d2-ae6a-843d1df55559"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Hareesh\\PycharmProjects\\Framework_POM_9\\conftest.py\", line 13, in test_setup\n    driver = webdriver.Chrome(executable_path=\"C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\Framework_POM\\\\drivers\\\\chromedriver.exe\")\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1555502877480, "stop": 1555502877481}], "start": 1555502877480, "stop": 1555502877705}