{"uuid": "50012fdd-b2ab-4275-9853-998a716d1ab5", "children": ["12433242-5eea-4881-b59b-d6df652c1be7", "797a28a1-2861-45ad-b4ee-ce81e59186ab"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Hareesh\\PycharmProjects\\Framework_POM_9\\conftest.py\", line 13, in test_setup\n    driver = webdriver.Chrome(executable_path=\"C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\Framework_POM\\\\drivers\\\\chromedriver.exe\")\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Hareesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1555669786211, "stop": 1555669786211}], "start": 1555669786211, "stop": 1555669786430}